sudo: false

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.7

jdk:
  - oraclejdk8

after_success:
  - TRAVIS_BRANCH = $TRAVIS_BRANCH
  - echo TRAVIS_TAG = $TRAVIS_TAG
  - echo TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST
  - test -n "$TRAVIS_TAG" &&
    test "$TRAVIS_PULL_REQUEST" = "false" &&
    echo "just tag"
